# Generated by Django 5.2 on 2025-04-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='efpdatabase',
            table='public.efpdatabase',
        ),
    ]
