# Generated by Django 5.2 on 2025-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0003_efp_delete_efpdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('presenters', models.TextField(blank=True, null=True)),
                ('participants_female', models.IntegerField(blank=True, null=True)),
                ('schools', models.IntegerField(blank=True, null=True)),
                ('project', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public.workshop',
            },
        ),
    ]
