# Generated by Django 5.2 on 2025-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0004_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
