# Generated by Django 5.1.7 on 2025-03-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataview", "0002_alter_efpdatabase_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="efpdatabase",
            table="efp_database",
        ),
    ]
