# Generated by Django 5.1.7 on 2025-03-25 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataview", "0003_alter_efpdatabase_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="efpdatabase",
            options={"managed": False},
        ),
    ]
