# Generated by Django 5.1.7 on 2025-03-25 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataview", "0005_alter_efpdatabase_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="efpdatabase",
            table="public.EfpDatabase",
        ),
    ]
